inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/factories/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/**/*'
